# Working with arrays: NumPy

Python arrays are powerful, but they can confuse programmers familiar with other languages.  In this section an alternate method will be shown using a very powerful module called NumPy.

As shown in the previous section, Python arrays are indexed lists, and you can access a list element using an integer index (or range).  For example,

In [1]:
myList=[1,2,3,4]
print(myList[2])

3


As well as simple indexing Python allows you to use a slicer notation to specify parts of the list. A slicer has the form:
<ul>
  <li>start:end	items from start through end-1
  <li>start:		items from start to the end of the array
  <li>:end		items from the start to end-1
  <li>:		    items from start to end
</ul>

As a reminder, the slicer doesn't include the end element. For example myList[0:2] is just elements 0 and 1 and not element 2.  That is, start specifies the first element in the selection and end specifies the first element not in the selection. 

You can also use negative values for start and end and this is interpreted as counting from the end of the list.  For example myList[-2:] is [3,4] and myList[-3:-1] is [2,3].

Finally you can include a step size as a third value in the slicer, i.e., [start:end:step]. For example myList[0:3:2] is [1,3].  As you can leave out specification and just use : you can write myList[::2] for example to step though the entire list taking every other element.  It is also worth noting that is a slicer doesn't specify any elements of the list, for example myList[4:2] then the result is a null list rather than an error.

Slicing notation can be used to extract elements and to store elements, i.e., on the left and the right of an assignment.   For example:

myList[1:3]=myList[0:2]

stores elements [0] and [1] in elements [1] and [2].

Slicing notation is the main way in which Python differs from other languages in its use of lists as arrays.  You can also write compact for loops using comprehensions.  A comprehension is just a for loop that generates a sequence of values that you can use to generate a list.  For example:

In [2]:
myList=[i for i in range(10)]
print(myList)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


You can see this as a way of writing compact loops but it is also a way of manipulating lists to create new lists.  For example

In [3]:
newList=[myList[i] for i in range(1,3)]
print(newList)

[1, 2]


Now we have revised slicing and comprehensions, it is time to take a look at some of the problems and some of the solutions.

In Python a 2D array is simply a list of lists. For example, a 2x2 matrix could be represented as:

    myArray=[[1,2],[3,4]]

which is a list of two lists which represent the rows of the matrix.  You can use slicing and comprehensions on multi-dimensional arrays but they don't always work as you might hope.  For example, how could you extract a sub-matrix? The obvious answer is to use slicing.  Given the 3x3 array:

    myArray=[[1,2,3],[4,5,6],[7,8,9]]

you might imagine that you could extract the 2x2 matrix in its top right-hand corner using:

    myArray[0:2][0:2]

However, this doesn't work and what you get is:

    [[1, 2, 3], [4, 5, 6]]

If you think about it this is perfectly reasonable. The first slicer specifies the first two elements of the list, and these are the first two rows, i.e. 

    myArray[0:2]

is 

    [[1, 2, 3], [4, 5, 6]]

Now you can see what goes wrong with the second slicer - it isn't operating on the rows it is stil operating on the outer list. So it returns [[1, 2, 3], [4, 5, 6]] [0:2] which is just the first two rows again.  Slicing notation works perfectly and as advertised, but it is common to think that it will do more.

If you want to extract the sub-matrix then the simplest way is to use a list comprehension or the equivalent for loops:

    [[myArray[i][j] for j in range(2) ] for i in range(2)]

that returns [[1, 2], [4, 5]].  This is a nice compact way of writing it, but it is not a lot different to a pair of nested index loops.  

If you have used Matlab or Octave you might also expect Python to support matrix functions.  For example, to take the square root element-wise you might try:

    math.sqrt(myArray)

but this doesn't work. The majority of Python math functions accept a single scalar argument and trying to use them on an array simply generates an error.   The simplest way around this problem is to use the map function which applies the function specified as its first argument to the list specified as its second argument. 

    list(map(math.sqrt,myList))

In Python 3 map returns an iterable which has to be converted to a list - in Python 2 map returns the list directly.  This looks neat but in practice it isn't really much use. For example suppose you want the elementwise square root of a 3x3 matrix then

    list(map(math.sqrt,myArray))

fails because sqrt is passed each row of the matrix in turn and it expects a scalar.  In Python 3 map has been down-graded without actually being removed and it is better to write a list comprehension. For example:

    [math.sqrt(x) for x in myList]

performs an elementwise square root on the one-dimensional myList.  The more than one dimensional case is on a little more complicated:

    [[math.sqrt(x) for x in row] for row in myArray]

or if you prefer to use an index loop (we'll see this next):

    [[math.sqrt(myArray[i][j]) 
       for j in range(len(myArray)) ] 
           for i in range(len(myArray))]


Arrays in Python work reasonably well but compared to Matlab or Octave there are a lot of missing features. There is an array module that provides something more suited to numerical arrays but why stop there as there is also NumPy which provides a much better array object.  Put simply if you are going to use something other than the basic Python list as an array you might as well download NumPy - which is available for Python 2 and 3. 

Assuming you have NumPy installed, all you need to do to use it is add: 

import numpy as np

to the start of any program.  The main thing that NumPy brings to the environment is the NumPy array.  This is an object, complete with methods, that wraps a static array of various data types.  Notice that the NumPy array is a completely separate data type from the Python list and this means you can have two types of array-like entity within your program. The good news is that it is very easy to convert Python data types that are "array-like" to NumPy arrays.

It is also good that NumPy arrays behave a lot like Python arrays with the two exceptions - the elements of a NumPy array are all of the same type and have a fixed and very specific data type and once created you can't change the size of a NumPy array.  A Python array is dynamic and you can append new elements and delete existing ones. A NumPy array is more like an object-oriented version of a traditional C or C++ array.

You can create NumPy arrays using a large range of data types from int8, uint8, float64, bool and through to complex128. Check the documentation of what is available. There is also a range of type conversion functions available. 

To create a NumPy array you can use the low-level constructor ndarray. You can pass this a range of arguments to control the type of array you create but the simplest is to pass just the shape of the array. For example:

In [4]:
import numpy as np
myArray = np.ndarray((3,3))
print(myArray)

[[2.33605760e-310 4.64217953e-310 2.33606387e-310]
 [2.33606387e-310 2.33606387e-310 2.33607781e-310]
 [1.73316021e-260 5.08162503e-299 2.74701092e-260]]


The array is created in memory and uninitialized (sort of). This means that if you try to make use of any of the elements of myArray you will find some random garbage.   A more usual way of creating an array is to use one of either np.zeros(shape) or np.ones(shape) which create an array of the shape specified initialized to zeros or ones respectively.  Similarly

np.arange(start,end,increment)

will create a one dimensional array initialized to values from start to end spaced by increment. There is also the linspace method that will create an array of a specified size with evenly spaced values.

In [5]:
import numpy as np

# this will create an array starting at 5, ending at 100, incrementing by 10
myArray = np.arange(5,100,10)
print(myArray)

# this will create an array starting at 5, ending at 20, having 10 total points
myNewArray = np.linspace(5,20,10)
print(myNewArray)

[ 5 15 25 35 45 55 65 75 85 95]
[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


There are lots of other array creation methods including random, identity and so on. 
You can also use the array method to convert a Python array object into a NumPy array. For example:

In [6]:
import numpy as np
myArray=np.array([[1,2,3],[4,5,6],[7,8,9]])

Now that we can create a NumPy array it's time to find out how to use them.  You can index a NumPy array just like a Python array. So for example to find what's in the second row, third column (i.e., the number 6):
(recall python starts counting at zero!!):

In [7]:
import numpy as np
myArray=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print 2nd row (index=1) and third column (index=2):
print(myArray[1][2])
# alternately like this (similar to matlab)
print(myArray[1,2])

6
6


You can use more complex slicing and it all works exactly as for a Python array.  For example:

Note in the above, that the NumPy array goes well beyond what a standard Python array supports in terms of indexing.  The first big difference is that you can use a tuple as an indexing object.  The simplest case of this is to use a tuple of integers.  For example, in

    myArray=np.array([[1,2,3],[4,5,6],[7,8,9]])

myArray[1,2] is 6.  If myArray was a simple Python array this would generate an error and you would have to write:

    myArray[1][2]

Both index methods work with NumPy arrays.  Being able to use a tuple of integers is a simplification of notation but you can go one step further and use a tuple of slicers.  The rule is that each slicer operates on its corresponding dimension. That is unlike the Python array where multiple slicers operate on the result of previous slicers the NumPy array implements things are you might want them to work, i.e., slicing each dimension in turn.  For example, if you now try:

    myArray[0:2,0:2]

you will discover that it does return the 2x2 sub matrix in the top left hand corner of the original array, i.e.,

    array([[1, 2],[4, 5]])

This works with any number of dimensions and each slicer is applied to the corresponding dimension to extract a sub-matrix. You can even use a step size to extract, say, every other row and column.  All you have to remember is to specify the slicers as part of a tuple and not as individual index terms.  Notice that if you don't specify one slicer for each dimension, the missing slicers are assumed to be :, i.e., the entire dimension. For example myArray[0:2] is taken to mean myArray[0:2,:].

You can also use the ellipsis object to add : slicers if you want to specify slicers from the other end of the dimensions.  For example if bigArray has five dimensions, bigArray[...,0] specifies all of the rows columns and so on but with the final dimension set to index 0, i.e., it is equivalent to bigArray[:,:,:,:,0].  Also notice that myArray[0,:] is array([1, 2, 3]), i.e., row zero all column entries as a one dimensional array, but myArray[0:1,:] is array([[1, 2, 3]]), i.e., a two dimensional array consisting of just row zero.  In general using an integer i returns an array with one less dimension than using the slicer [i:i+1] which returns the same elements. 

NumPy arrays have other tricks when it comes to indexing mostly borrowed from Matlab and Octave.  For example, you can set up an indexing array of integers and these will be used to select elements along the corresponding dimension.  So, for example:

    myArray[[0,2],[1,2]]

picks out the myArray[0,1] and myArray[2,2], i.e., array([2, 9]).  You can use this technique to access arbitrary sub matrices of elements or regular sub matrices with indexes determined by other matrices.  There are lots of rules that govern how the lists of integers are applied, i.e., what happens if you don't specify enough lists and so on but they are all obvious defaults. 

Boolean indexing is another indexing method borrowed from Matlab and Octave.  You can use a Boolean array to pick out the elements you want to work with.  If the Boolean array has a true element then the element in the array being indexed is selected.  Now at first thought this doesn't sound like a very useful option.  Why would you go to the trouble of constructing a Boolean array to pick elements from an array?  The answer is because it is very easy.

One of the things that NumPy introduces is element-wise functions and operations including element-wise comparisons.  For example:

    myArray>1

produces a Boolean array:

    [[False, True, True],
    [ True, True, True],
    [ True, True, True]]

This makes is easy to index an array on a condition. For example, suppose you wanted to set every element of an array smaller than 0.1 to zero:

    myArray[myArray<0.1]=0

Now you can see why a Boolean index is useful!
 

There are many features of NumPy that are beyond the scope of this introduction but the availability of array functions is one that you need to know about.  NumPy provides many apparent redundant copies of functions that are already provided in math or other modules.  For example, np.sqrt seems to be identical to math.sqrt but it can be applied to arrays and it will be computed on each element:

    np.sqrt(myArray)

gives:

    array([[ 1. , 1.41421356, 1.73205081],
    [ 2. , 2.23606798, 2.44948974],
    [ 2.64575131, 2.82842712, 3. ]])

If you want to compute an element-wise function on a NumPy array then check to see if it is provided within NumPy first - there are a lot of functions for general mathematics, bit manipulation and matrix arithmetic.  For example, to multiply two matrices together, AB just use A.dot(B).

# Program flow
As with many other programming and scripting languages there are different ways to step or parse through numbers, values and commands.  Here we will discuss four of these: if, while, for and try.  These all serve different purposes but can be used in very similar ways.  The syntax in python is also similar for all, namely, the code block starts with the statement followed by a colon (:).  There is no end statement, just indented code to indicate the block.

The first example is an “if” statement.  Note that “if” can also have subsequent “elif” (“elseif”) or “else” statements:

In [8]:
x = 4
y = 0
if x > 5:
   y = x * x
   z = 2 * x
   print(z)
print(y)

0


Note here that parentheses are not used in the qualifier check.  The middle two lines will only be executed if the qualifier is true (they are indented lines below the if statement).  The last line, not indented, will always execute.  “if” statements can also take “and/or”:

In [9]:
if x > 5 and x < 10:
   y = x * x
   z = 2 * y
else:
   y = 0
   z = 0
print(y,z)

0 0


A similar function is provided using the “while” statement.  In this case, the code will run as long as the statement is true, unlike an “if” statement that will run once.

In [10]:
i = 4
while i < 9:
   print(i)
   i = i + 1
print("Loop done")

4
5
6
7
8
Loop done


The third bit of coding that involves a decision block is a “for loop”. These exist in almost all languages in some form or another. In python, the syntax again is with a leading line starting with “for”, ending with a “:”, and subsequent code to be executed indented. The first line includes both the index/counting variable and the constraint. This can take many different forms. One option is using a variable:

In [11]:
x = [1, 4, 9, 25, 36]
for i in x:
   print(i)
print("Done for loop")

1
4
9
25
36
Done for loop


Another option is to use the "internal" range function:

In [12]:
for i in range(10,20):
   print (i)
print("Done for loop")

10
11
12
13
14
15
16
17
18
19
Done for loop


# scripting
Now we can start to put things together in a simple script.  Much like Matlab, we simply enter the python commands into a file, then run that file.  Thus far we’ve entered commands one by one into the python interpreter.  A more common way to run python commands is to include them into a file, then “run” that file.  This helps preserve code but also provides efficiencies (e.g., if you make a mistake you don’t have to go back to the start and enter all the commands again).  Typically, python scripts end with the suffix .py.  

The first thing to consider when writing scripts is to properly comment the code.  In python this is done with a hash (#), and it can occur anywhere in the line (everything after, and including, the hash sign is ignored by the interpreter).  Multi-line comments can be enabled by starting with three single quotes (‘’’) and then ending the comment block with another three quotes.

Here is a straightforward example script to print out 10 successive random numbers.  A random number generator is found in the package called “random”

In [13]:
'''
This is a sample script to make some random numbers

JimP 04-29-2020
'''

#
# sample python script that will stream out a set of random numbers
# 

# first we import the "random" package, and note to access any modules in this
#   package, we preceed the module with the package name (since we do not alias)
import random

# set the sample size to 10, i.e., we'll generate 10 random numbers
sampleSize = 10

# now we loop over our sample size (aka, sampleSize, aka 10); recall here
#   that we'll start at 0 and go to 9, but still get ten interations
for i in range(sampleSize):
    newValue = random.random()
    print (i,newValue)

0 0.33522113723871116
1 0.7224244453753969
2 0.8479531990267535
3 0.5246598588300175
4 0.7852447653865595
5 0.8318972942577864
6 0.9969939325567985
7 0.708636286125749
8 0.9279773231262797
9 0.768734777072413


We can now expand our little script to actually read from input the number of numbers to generate, rather than fix it in the script.  For this, we'll use the function input:

In [15]:
'''
This is a sample script to make some random numbers

JimP 04-29-2020
'''

#
# sample python script that will stream out a set of random numbers
# 

# first we import the "random" package, and note to access any modules in this
#   package, we preceed the module with the package name (since we do not alias)
import random

# read sample size from keyboard input
sampleSize = input('Enter sample size: ')

# now we loop over our sample size (aka, sampleSize, aka 10); recall here
#   that we'll start at 0 and go to 9, but still get ten interations
for i in range(sampleSize):
    newValue = random.random()
    print (i,newValue)

Enter sample size:  4


TypeError: 'str' object cannot be interpreted as an integer

What happened here? It turns out the standard input, as returned by "input" comes back as type str, a string, but we want an integer, so we have to change that:

In [16]:
'''
This is a sample script to make some random numbers

JimP 04-29-2020
'''

#
# sample python script that will stream out a set of random numbers
# 

# first we import the "random" package, and note to access any modules in this
#   package, we preceed the module with the package name (since we do not alias)
import random

# read sample size from keyboard input and then convert it to integer
sampleSize = input('Enter sample size: ')
sampleSize = int(sampleSize)

# set the "seed" for our random numbers (seed being a module in random)
random.seed()

# now we loop over our sample size (aka, sampleSize, aka 10); recall here
#   that we'll start at 0 and go to 9, but still get ten interations
for i in range(sampleSize):
    newValue = random.random()
    print (i,newValue)

Enter sample size:  5


0 0.48992283418371463
1 0.5296807687706494
2 0.8744942985294452
3 0.2504808566046678
4 0.2537598046133869


Let's now make this a little more fancy by adding the time.  There is a whole slew of ways to deal with time, but here we'll stick with the package "time".  Dealing with time will be a constant challenge, but hopefully you'll come to see that some python packages are able to do this quite easily.

In [17]:
'''
This is a sample script to make some random numbers

JimP 04-29-2020
'''

#
# sample python script that will stream out a set of random numbers
# 

# first we import the "random" package, and note to access any modules in this
#   package, we preceed the module with the package name (since we do not alias)
#   and next we import the "time" package
import random
import time

# read sample size from keyboard input and then convert it to integer
sampleSize = input('Enter sample size: ')
sampleSize = int(sampleSize)

# set the "seed" for our random numbers (seed being a module in random)
random.seed()

# now we loop over our sample size; we now add the time
for i in range(sampleSize):
    newValue = random.random()
    newValue = random.random()
    date = time.strftime("%x")
    now  = time.strftime("%X")
    print(date, now, newValue)
    time.sleep(2)

Enter sample size:  8


11/06/20 02:01:52 0.3291174331028931
11/06/20 02:01:54 0.06411914316940281
11/06/20 02:01:56 0.5405377820695155
11/06/20 02:01:58 0.036246466241141806
11/06/20 02:02:00 0.5514700287966332
11/06/20 02:02:02 0.06244538458760729
11/06/20 02:02:04 0.6363741716819227
11/06/20 02:02:06 0.4822831687279955
